###
# Sample Guardfile block for Guard::ImageOptim
#
# :input         ("images") set input image directory
# :notifications (true)     toggle guard notifications
# :run_at_start  (false)    optimize images when guard starts
# :pngout        (false)    toggle pngout for image_optim gem
# :svgo          (false)    toggle svgo for image_optim gem
###
guard :image_optim, :input => "images"
